# Generated by Django 6.1 on 2026-08-17 07:45

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('exchange_rates', '0002_exchangerate'),
        ('finances', '0001_initial'),
        ('incomes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'number',
                    models.CharField(max_length=100, verbose_name='Номер выставляемого счёта'),
                ),
                ('issue_date', models.DateField(verbose_name='Дата выставления')),
                (
                    'service_period_start',
                    models.DateField(
                        blank=True, null=True, verbose_name='Начало периода оказания услуги'
                    ),
                ),
                (
                    'service_period_end',
                    models.DateField(
                        blank=True, null=True, verbose_name='Конец периода оказания услуги'
                    ),
                ),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок оплаты')),
                (
                    'language',
                    models.CharField(
                        choices=[('ru', 'Русский'), ('en', 'English'), ('ka', 'ქართული')],
                        default='ru',
                        max_length=10,
                        verbose_name='Язык',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('created', 'Создан'),
                            ('pending', 'Ожидает оплаты'),
                            ('paid', 'Оплачен'),
                            ('cancelled', 'Отменён'),
                        ],
                        default='created',
                        max_length=30,
                        verbose_name='Статус',
                    ),
                ),
                (
                    'seller_snapshot',
                    models.JSONField(default=dict, verbose_name='Снимок данных продавца'),
                ),
                (
                    'buyer_snapshot',
                    models.JSONField(default=dict, verbose_name='Снимок данных покупателя'),
                ),
                (
                    'payment_details_snapshot',
                    models.JSONField(default=dict, verbose_name='Снимок платёжных реквизитов'),
                ),
                (
                    'subtotal',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                        verbose_name='Сумма до скидок и наценок',
                    ),
                ),
                (
                    'discount_amount',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                        verbose_name='Сумма скидки',
                    ),
                ),
                (
                    'extra_charge_amount',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                        verbose_name='Дополнительная наценка',
                    ),
                ),
                (
                    'total_amount',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                        verbose_name='Итоговая сумма',
                    ),
                ),
                ('tax_note', models.TextField(blank=True, verbose_name='Примечание о налоге')),
                (
                    'tax_reference_amount',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                        verbose_name='Справочная налоговая сумма',
                    ),
                ),
                (
                    'payment_purpose',
                    models.CharField(blank=True, max_length=255, verbose_name='Назначение платежа'),
                ),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                (
                    'pdf_file',
                    models.FileField(
                        blank=True, null=True, upload_to='invoices/', verbose_name='PDF-инвойс'
                    ),
                ),
                (
                    'pdf_checksum',
                    models.CharField(
                        blank=True, max_length=64, verbose_name='Контрольная сумма PDF'
                    ),
                ),
                (
                    'generated_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='Дата генерации PDF'),
                ),
                (
                    'sent_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки'),
                ),
                (
                    'paid_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
                ),
                (
                    'cancelled_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены'),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
                ),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                (
                    'counterparty',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='invoices',
                        to='finances.counterparty',
                        verbose_name='Контрагент',
                    ),
                ),
                (
                    'currency',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='invoices',
                        to='exchange_rates.currency',
                        verbose_name='Валюта',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='invoices',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('position', models.PositiveIntegerField(verbose_name='Номер позиции')),
                ('description', models.CharField(max_length=255, verbose_name='Описание позиции')),
                (
                    'quantity',
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal('1.000'),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal('0.001'))],
                        verbose_name='Количество',
                    ),
                ),
                (
                    'unit',
                    models.CharField(
                        default='service', max_length=50, verbose_name='Единица измерения'
                    ),
                ),
                (
                    'unit_price',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                        verbose_name='Стоимость за единицу',
                    ),
                ),
                (
                    'line_total',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                        verbose_name='Итоговая стоимость позиции',
                    ),
                ),
                (
                    'invoice',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='invoice_items',
                        to='invoices.invoice',
                        verbose_name='Инвойс',
                    ),
                ),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator('0.01')],
                        verbose_name='Сумма оплаты',
                    ),
                ),
                ('paid_at', models.DateTimeField(verbose_name='Дата и время оплаты')),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
                ),
                (
                    'currency',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='invoice_payments',
                        to='exchange_rates.currency',
                        verbose_name='Валюта оплаты',
                    ),
                ),
                (
                    'income_entry',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='invoice_payments',
                        to='incomes.incomeentry',
                        verbose_name='Поступление',
                    ),
                ),
                (
                    'invoice',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='payments',
                        to='invoices.invoice',
                        verbose_name='Инвойс',
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', 'status'], name='invoices_in_user_id_ebcfda_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(
                fields=['user', 'issue_date'], name='invoices_in_user_id_3940ad_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(
                fields=('user', 'number'), name='unique_invoice_number_per_user'
            ),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.UniqueConstraint(
                fields=('invoice', 'position'), name='unique_invoice_item_position'
            ),
        ),
    ]
