# Generated by Django 6.1 on 2026-08-22 14:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rates', '0002_exchangerate'),
        ('incomes', '0002_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('pending', 'Ожидает оплаты'), ('partially_paid', 'Частично оплачен'), ('paid', 'Оплачен'), ('cancelled', 'Отменён')], default='created', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма оплаты'),
        ),
        migrations.AddConstraint(
            model_name='invoicepayment',
            constraint=models.UniqueConstraint(fields=('invoice', 'income_entry'), name='unique_invoice_income_payment'),
        ),
    ]
