# Generated by Django 6.1 on 2026-08-12 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConnection',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'telegram_user_id',
                    models.BigIntegerField(unique=True, verbose_name='Telegram User ID'),
                ),
                ('telegram_chat_id', models.BigIntegerField(verbose_name='Telegram Chat ID')),
                (
                    'username',
                    models.CharField(blank=True, max_length=64, verbose_name='Username в Telegram'),
                ),
                (
                    'first_name',
                    models.CharField(blank=True, max_length=255, verbose_name='Имя в Telegram'),
                ),
                (
                    'last_name',
                    models.CharField(blank=True, max_length=255, verbose_name='Фамилия в Telegram'),
                ),
                (
                    'language_code',
                    models.CharField(blank=True, max_length=10, verbose_name='Язык Telegram'),
                ),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная связь')),
                (
                    'linked_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Дата подключения'),
                ),
                (
                    'last_seen_at',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='Последняя активность'
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='telegram_connection',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(fields=['telegram_chat_id'], name='telegram_in_telegra_1d4d42_idx')
                ],
            },
        ),
    ]
