# Generated by Django 6.1 on 2026-08-17 07:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Месяц')),
                ('field_18', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Доходы через кассовый аппарат')),
                ('field_19', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Доходы через физический POS-терминал')),
                ('field_20', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Поступления на расчётные счета и другие безналичные расчёты')),
                ('field_21', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Прочие доходы, включая бартер и операции по договорам с криптовалютой')),
                ('field_17', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Сумма дохода за предыдущий месяц')),
                ('field_15', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Нарастающий итог с начала календарного (налогового) года')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Налоговая ставка')),
                ('field_26', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Сумма налога')),
                ('calculation_status', models.CharField(default='pending', max_length=30, verbose_name='Статус расчёта')),
                ('declaration_status', models.CharField(default='not_submitted', max_length=30, verbose_name='Статус декларации')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подачи декларации')),
                ('submission_comment', models.TextField(blank=True, verbose_name='Комментарий к подаче')),
                ('submission_confirmation', models.FileField(blank=True, null=True, upload_to='taxes/submissions/', verbose_name='Подтверждение подачи')),
                ('payment_status', models.CharField(default='not_paid', max_length=30, verbose_name='Статус оплаты')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Оплаченная сумма')),
                ('payment_comment', models.TextField(blank=True, verbose_name='Комментарий к оплате')),
                ('payment_confirmation', models.FileField(blank=True, null=True, upload_to='taxes/payments/', verbose_name='Подтверждение оплаты')),
                ('deadline', models.DateField(verbose_name='Крайний срок')),
                ('is_overdue', models.BooleanField(default=False, verbose_name='Просрочено')),
                ('changed_after_submission', models.BooleanField(default=False, verbose_name='Изменено после подачи')),
                ('calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата расчёта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'deadline'], name='taxes_taxpe_user_id_165475_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'year', 'month'), name='unique_tax_period_per_user'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='tax_period_valid_month')],
            },
        ),
    ]
