# Generated by Django 6.0.3 on 2026-08-21 07:02

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxperiod',
            name='field_17',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                verbose_name='Общая сумма дохода за месяц',
            ),
        ),
    ]
