# Generated by Django 6.1 on 2026-08-17 07:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(verbose_name='Дата и время получения дохода')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Способ оплаты')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='Номер документа')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Дата документа')),
                ('original_amount', models.DecimalField(decimal_places=10, max_digits=28, validators=[django.core.validators.MinValueValidator(Decimal('1E-10'))], verbose_name='Сумма в исходной валюте')),
                ('exchange_rate_value', models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-10'))], verbose_name='Курс к GEL')),
                ('exchange_rate_unit', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество единиц валюты для курса')),
                ('exchange_rate_source', models.CharField(max_length=100, verbose_name='Источник курса')),
                ('exchange_rate_date', models.DateField(verbose_name='Дата курса')),
                ('exchange_rate_time', models.TimeField(blank=True, null=True, verbose_name='Время курса')),
                ('amount_gel', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма в GEL')),
                ('declaration_category', models.CharField(choices=[('cash_register_18', 'Доходы через кассовый аппарат'), ('physical_pos_19', 'Доходы через физический POS-терминал'), ('cashless_20', 'Поступления на расчётные счета и другие безналичные расчёты'), ('other_21', 'Прочие доходы, включая бартер и операции по договорам с криптовалютой')], max_length=50, verbose_name='Категория декларации')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Сумма НДС')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='income_attachments/', verbose_name='Вложение')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_entries', to='finances.counterparty', verbose_name='Контрагент')),
                ('financial_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_entries', to='finances.financialaccount', verbose_name='Финансовый счёт')),
            ],
        ),
    ]
