# Generated by Django 6.1 on 2026-09-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeentry',
            name='crypto_asset',
            field=models.CharField(blank=True, max_length=20, verbose_name='Криптовалюта'),
        ),
        migrations.AddField(
            model_name='incomeentry',
            name='crypto_network',
            field=models.CharField(blank=True, max_length=50, verbose_name='Сеть криптовалюты'),
        ),
        migrations.AddField(
            model_name='incomeentry',
            name='crypto_tx_hash',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hash криптотранзакции'),
        ),
        migrations.AddField(
            model_name='incomeentry',
            name='crypto_wallet_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес криптокошелька'),
        ),
    ]
