# Generated by Django 6.1 on 2026-08-12 15:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepreneurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255, verbose_name='Название бизнеса')),
                ('entrepreneur_status', models.CharField(blank=True, max_length=100, verbose_name='Статус предпринимателя')),
                ('tin', models.CharField(max_length=50, verbose_name='ИНН')),
                ('legal_address', models.CharField(blank=True, max_length=255, verbose_name='Юридический адрес')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('public_email', models.EmailField(blank=True, max_length=254, verbose_name='Публичный email')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Налоговая ставка')),
                ('accounting_start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала учёта')),
                ('timezone', models.CharField(default='Asia/Tbilisi', max_length=50, verbose_name='Часовой пояс')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('ka', 'ქართული')], default='ru', max_length=10, verbose_name='Язык')),
                ('invoice_prefix', models.CharField(default='INV-', max_length=20, verbose_name='Префикс инвойса')),
                ('next_invoice_number', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Следующий номер инвойса')),
                ('signature_file', models.FileField(blank=True, null=True, upload_to='signatures/', verbose_name='Подпись')),
                ('logo_file', models.FileField(blank=True, null=True, upload_to='logos/', verbose_name='Логотип')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrepreneur_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
