"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent


load_dotenv()

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'accounts',
    'finances',
    'incomes',
    'exchange_rates',
    'invoices',
    'taxes',
    'notifications',
    'telegram_integration',
    'audit',
    'uploads',
    'idempotency',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

DATABASES = {'default': dj_database_url.config(default=os.getenv('DATABASE_URL'))}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv('TIME_ZONE', 'UTC')

USE_I18N = True

USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': ('drf_spectacular.openapi.AutoSchema'),
    'DEFAULT_AUTHENTICATION_CLASSES': [
        ('accounts.authentication.VersionedJWTAuthentication'),
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'config.renderers.APIJSONRenderer',
    ],
    'EXCEPTION_HANDLER': ('config.exceptions.api_exception_handler'),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Georgia IE Platform API',
    'DESCRIPTION': 'Документация для API платформы Georgia IE',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

AUTH_USER_MODEL = 'accounts.User'

INVOICE_PDF_FONT_PATH = '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'

INVOICE_PDF_FONT_BOLD_PATH = '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'

BUSINESS_TIME_ZONE = os.getenv(
    'BUSINESS_TIME_ZONE',
    'Asia/Tbilisi',
)

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': (timedelta(minutes=15)),
    'REFRESH_TOKEN_LIFETIME': (timedelta(days=7)),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

DEFAULT_FROM_EMAIL = os.getenv(
    'DEFAULT_FROM_EMAIL',
    'noreply@georgia-ie.local',
)

PASSWORD_RESET_FRONTEND_URL = os.getenv(
    'PASSWORD_RESET_FRONTEND_URL',
    ('http://localhost:5173/reset-password'),
)

TELEGRAM_BOT_TOKEN = os.getenv(
    'TELEGRAM_BOT_TOKEN',
    '',
)

TELEGRAM_WEBHOOK_SECRET = os.getenv(
    'TELEGRAM_WEBHOOK_SECRET',
    '',
)

TELEGRAM_INIT_DATA_MAX_AGE = int(
    os.getenv(
        'TELEGRAM_INIT_DATA_MAX_AGE',
        '600',
    )
)

INVOICE_SHARE_TTL_HOURS = int(
    os.getenv(
        'INVOICE_SHARE_TTL_HOURS',
        '24',
    )
)

FILE_DOWNLOAD_LINK_TTL = int(
    os.getenv(
        'FILE_DOWNLOAD_LINK_TTL',
        '900',
    )
)

MAX_UPLOAD_SIZE = int(
    os.getenv(
        'MAX_UPLOAD_SIZE',
        str(10 * 1024 * 1024),
    )
)
