# Generated by Django 6.1 on 2026-08-12 16:02

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('exchange_rates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('rate_date', models.DateField(verbose_name='Дата курса')),
                ('rate_time', models.TimeField(blank=True, null=True, verbose_name='Время курса')),
                (
                    'rate_value',
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(Decimal('1E-10'))],
                        verbose_name='Значение курса',
                    ),
                ),
                (
                    'rate_unit',
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name='Количество единиц валюты',
                    ),
                ),
                ('source', models.CharField(max_length=100, verbose_name='Источник курса')),
                (
                    'is_manual',
                    models.BooleanField(default=False, verbose_name='Курс введён вручную'),
                ),
                (
                    'raw_reference',
                    models.TextField(blank=True, verbose_name='Исходная ссылка или данные'),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_exchange_rates',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'currency',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='exchange_rates',
                        to='exchange_rates.currency',
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(
                        fields=['currency', 'rate_date'], name='exchange_ra_currenc_102fac_idx'
                    )
                ],
            },
        ),
    ]
