# Generated by Django 6.1 on 2026-08-12 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchange_rates', '0002_exchangerate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название или имя')),
                ('type', models.CharField(choices=[('individual', 'Физическое лицо'), ('entrepreneur', 'Индивидуальный предприниматель'), ('company', 'Компания')], max_length=20, verbose_name='Тип контрагента')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='Налоговый номер')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'name'], name='finances_co_user_id_dc5b44_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название счёта')),
                ('type', models.CharField(choices=[('bank_account', 'Банковский счёт'), ('bank_card', 'Банковская карта'), ('cash', 'Наличные'), ('physical_pos', 'Физический POS-терминал'), ('payment_system', 'Платёжная система'), ('crypto_wallet', 'Криптокошелёк'), ('other', 'Другое')], max_length=30, verbose_name='Тип счёта')),
                ('provider_name', models.CharField(blank=True, max_length=100, verbose_name='Банк или провайдер')),
                ('account_holder', models.CharField(blank=True, max_length=255, verbose_name='Владелец счёта')),
                ('iban', models.CharField(blank=True, max_length=50, verbose_name='IBAN')),
                ('swift_bic', models.CharField(blank=True, max_length=20, verbose_name='SWIFT/BIC')),
                ('account_identifier', models.CharField(blank=True, max_length=255, verbose_name='Идентификатор счёта')),
                ('crypto_asset', models.CharField(blank=True, max_length=20, verbose_name='Криптовалюта')),
                ('crypto_network', models.CharField(blank=True, max_length=50, verbose_name='Сеть криптовалюты')),
                ('wallet_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес криптокошелька')),
                ('memo_tag', models.CharField(blank=True, max_length=100, verbose_name='Memo/Tag')),
                ('default_declaration_category', models.CharField(blank=True, choices=[('cash_register_18', 'Доходы через кассовый аппарат'), ('physical_pos_19', 'Доходы через физический POS-терминал'), ('cashless_20', 'Поступления на расчётные счета и другие безналичные расчёты'), ('other_21', 'Прочие доходы, включая бартер и операции по договорам с криптовалютой')], max_length=50, verbose_name='Категория декларации по умолчанию')),
                ('payment_instructions', models.TextField(blank=True, verbose_name='Инструкция для оплаты')),
                ('is_default', models.BooleanField(default=False, verbose_name='Счёт по умолчанию')),
                ('use_in_invoices', models.BooleanField(default=False, verbose_name='Использовать в инвойсах')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный счёт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('default_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_accounts', to='exchange_rates.currency', verbose_name='Валюта по умолчанию')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='finances_fi_user_id_4a8f0c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_financial_account_per_user')],
            },
        ),
    ]
