# Generated by Django 6.1 on 2026-08-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaccount',
            name='type',
            field=models.CharField(choices=[('bank_account', 'Банковский счёт'), ('bank_card', 'Банковская карта'), ('cash', 'Наличные'), ('cash_register', 'Кассовый аппарат'), ('physical_pos', 'Физический POS-терминал'), ('payment_system', 'Платёжная система'), ('crypto_wallet', 'Криптокошелёк'), ('other', 'Другое')], max_length=30, verbose_name='Тип счёта'),
        ),
    ]
