# Generated by Django 6.1 on 2026-08-17 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_enabled', models.BooleanField(default=True, verbose_name='Внутренние уведомления')),
                ('telegram_enabled', models.BooleanField(default=False, verbose_name='Уведомления в Telegram')),
                ('email_enabled', models.BooleanField(default=False, verbose_name='Email-уведомления')),
                ('send_time', models.TimeField(blank=True, null=True, verbose_name='Время отправки уведомления')),
                ('tax_reminders_enabled', models.BooleanField(default=True, verbose_name='Напоминания о налогах')),
                ('invoice_reminders_enabled', models.BooleanField(default=True, verbose_name='Напоминания об инвойсах')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('related_object_type', models.CharField(blank=True, max_length=100, verbose_name='Тип связанного объекта')),
                ('related_object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID связанного объекта')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='Ссылка действия')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Запланировано на')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения')),
                ('telegram_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки в Telegram')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки по Email')),
                ('delivery_status', models.CharField(default='pending', max_length=30, verbose_name='Статус доставки')),
                ('deduplication_key', models.CharField(blank=True, max_length=255, verbose_name='Ключ дедупликации')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка доставки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'scheduled_for'], name='notificatio_user_id_958dff_idx'), models.Index(fields=['user', 'read_at'], name='notificatio_user_id_47e85c_idx')],
            },
        ),
    ]
